apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-starter
  template:
    metadata:
      labels:
        app: backend-starter
    spec:
      containers:
        - name: backend-starter
          image: de.icr.io/default/backend-starter:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-starter-service
  labels:
    app: backend-starter-service
spec:
  selector:
    app: backend-starter
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
